[package]
name = "micropayment_hash"
version = "1.0.0"
authors = []

[addresses]
self='9aecfa45968542547a75860eb12c77e4263edef87113c8abc3fa0ee6c127551d'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
